[tool.poetry]
name = "oh-my-store"
version = "0.1.0"
description = ""
authors = ["anemone <annamatskecich866@gmail.com>"]
packages = [{ include = "oh-my-store", from = "src" }]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.11"
sqlalchemy = "^2.0.39"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"mk

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
